def create_structure(target_dir):
    import os

    folders = {
        "images": [],
        "videos": [],
        "docs": ["usage.md"],
        "scripts": ["process.py"],
        "output": []
    }

    for folder, files in folders.items():
        folder_path = os.path.join(target_dir, folder)
        os.makedirs(folder_path, exist_ok=True)
        for file in files:
            file_path = os.path.join(folder_path, file)
            with open(file_path, "w") as f:
                if file == "process.py":
                    f.write(
                        "#!/usr/bin/env python3\n\n"
                        "def main():\n"
                        "    print('Process your images/videos here')\n\n"
                        "if __name__ == '__main__':\n"
                        "    main()\n"
                    )
                elif file == "usage.md":
                    f.write("# Usage\n\nInstructions for processing media.\n")

    with open(os.path.join(target_dir, "README.md"), "w") as f:
        f.write("# Media Project\n\nGenerated by Plotonix.\n")

    with open(os.path.join(target_dir, "LICENSE"), "w") as f:
        f.write("MIT License\n")

    with open(os.path.join(target_dir, ".gitignore"), "w") as f:
        f.write("*.pyc\n__pycache__/\n.env\noutput/\n")

    print("Images/Media project structure created successfully!")
