def create_structure(target_dir):
    import os

    folders = {
        "src": ["main.py"],
        "tests": ["test_main.py"],
        "docs": ["usage.md"],
        "venv": []  # opsiyonel, virtual environment için
    }

    for folder, files in folders.items():
        folder_path = os.path.join(target_dir, folder)
        os.makedirs(folder_path, exist_ok=True)
        for file in files:
            file_path = os.path.join(folder_path, file)
            with open(file_path, "w") as f:
                if file == "main.py":
                    f.write(
                        "#!/usr/bin/env python3\n\n"
                        "def main():\n"
                        "    print('Hello, Python Project!')\n\n"
                        "if __name__ == '__main__':\n"
                        "    main()\n"
                    )
                elif file == "test_main.py":
                    f.write(
                        "def test_dummy():\n"
                        "    assert True\n"
                    )
                elif file == "usage.md":
                    f.write("# Usage\n\nInstructions to run your Python project.\n")

    with open(os.path.join(target_dir, "README.md"), "w") as f:
        f.write("# Python Project\n\nGenerated by Plotonix.\n")

    with open(os.path.join(target_dir, "LICENSE"), "w") as f:
        f.write("MIT License\n")

    with open(os.path.join(target_dir, ".gitignore"), "w") as f:
        f.write("*.pyc\n__pycache__/\n.env\nvenv/\n")

    print("Python project structure created successfully!")
