def create_structure(target_dir):
    import os

    folders = {
        "bin": ["tool.py"],
        "docs": ["usage.md"],
        "tests": ["test_tool.py"],
        "configs": []
    }

    for folder, files in folders.items():
        folder_path = os.path.join(target_dir, folder)
        os.makedirs(folder_path, exist_ok=True)
        for file in files:
            file_path = os.path.join(folder_path, file)
            with open(file_path, "w") as f:
                if file == "tool.py":
                    f.write(
                        "#!/usr/bin/env python3\n\n"
                        "import sys\n\n"
                        "def main():\n"
                        "    print('Hello, CLI Tool!')\n"
                        "    print('Arguments:', sys.argv[1:])\n\n"
                        "if __name__ == '__main__':\n"
                        "    main()\n"
                    )
                elif file == "test_tool.py":
                    f.write(
                        "def test_dummy():\n"
                        "    assert True\n"
                    )
                elif file == "usage.md":
                    f.write("# Usage\n\nInstructions to run your CLI tool.\n")

    with open(os.path.join(target_dir, "README.md"), "w") as f:
        f.write("# CLI/Tool Project\n\nGenerated by Plotonix.\n")

    with open(os.path.join(target_dir, "LICENSE"), "w") as f:
        f.write("MIT License\n")

    with open(os.path.join(target_dir, ".gitignore"), "w") as f:
        f.write("*.pyc\n__pycache__/\n.env\n")

    print("CLI/Tool project structure created successfully!")
